// Generated by CoffeeScript 1.3.3

require(['models/calendar', 'views/calendar', 'jquery'], function(CalendarModel, CalendarView) {
  var calendar, calendarView;
  window.App = {
    Vent: _.extend({}, Backbone.Events)
  };
  calendar = new CalendarModel();
  return calendarView = new CalendarView({
    model: calendar
  }).render();
});
