// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Calendar = {
    Models: {},
    Collections: {},
    Views: {},
    Router: {}
  };

  window.vent = (function(_super) {

    __extends(vent, _super);

    function vent() {
      return vent.__super__.constructor.apply(this, arguments);
    }

    return vent;

  })(Backbone.Events);

}).call(this);
