// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Calendar.Models.Day = (function(_super) {

    __extends(Day, _super);

    function Day() {
      return Day.__super__.constructor.apply(this, arguments);
    }

    Day.prototype.defaults = {
      id: '',
      date: '',
      today: false
    };

    return Day;

  })(Backbone.Model);

  Calendar.Models.Calendar = (function(_super) {

    __extends(Calendar, _super);

    function Calendar() {
      return Calendar.__super__.constructor.apply(this, arguments);
    }

    return Calendar;

  })(Backbone.Model);

}).call(this);
