// Generated by CoffeeScript 1.3.3
(function() {
  var calendar, calendarView;

  calendar = new Calendar.Models.Calendar({
    month: 'Febuary',
    year: 2013,
    daysInWeek: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  });

  calendarView = new Calendar.Views.Calendar({
    model: calendar
  });

}).call(this);
