// Generated by CoffeeScript 1.3.3

define(['backbone', 'views/calendar', 'views/appointments'], function(Backbone, CalendarView, AppointmentsView) {
  var appointmentsView, calendarView;
  calendarView = new CalendarView();
  appointmentsView = new AppointmentsView();
  return calendarView;
});
