// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/calendar', 'views/calendarThead', 'views/calendarTbody'], function(CalendarModel, CalendarThead, CalendarTbody) {
  var CalendarTableView;
  CalendarTableView = (function(_super) {

    __extends(CalendarTableView, _super);

    function CalendarTableView() {
      return CalendarTableView.__super__.constructor.apply(this, arguments);
    }

    CalendarTableView.prototype.tagName = 'table';

    CalendarTableView.prototype.initialize = function() {
      this.calendarThead = new CalendarThead({
        model: this.model
      }).render();
      return this.calendarTbody = new CalendarTbody({
        model: this.model
      }).render();
    };

    CalendarTableView.prototype.render = function() {
      this.$el.append(this.calendarThead.el);
      this.$el.append(this.calendarTbody.el);
      return this;
    };

    return CalendarTableView;

  })(Backbone.View);
  return CalendarTableView;
});
