// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone'], function() {
  var DateModel;
  DateModel = (function(_super) {

    __extends(DateModel, _super);

    function DateModel() {
      return DateModel.__super__.constructor.apply(this, arguments);
    }

    DateModel.prototype.defaults = {
      date: ''
    };

    return DateModel;

  })(Backbone.Model);
  return DateModel;
});
