// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone', 'models/date'], function(Backbone, DateModel) {
  var DatesCollection;
  DatesCollection = (function(_super) {

    __extends(DatesCollection, _super);

    function DatesCollection() {
      return DatesCollection.__super__.constructor.apply(this, arguments);
    }

    DatesCollection.prototype.model = DateModel;

    return DatesCollection;

  })(Backbone.Collection);
  return DatesCollection;
});
